services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db # sửa lại thành mongo-data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_ROOT_ACCOUNT} # optional để login UI
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_ROOT_ACCOUNT}
    depends_on:
      - mongodb
volumes:
  mongo-data:
    external: true
    name: post_mongo-data
