services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nguyenthanh0399545598
      MONGO_INITDB_ROOT_PASSWORD: 8e9resHOxNvpj1Q0
    volumes:
      - mongo-data:/data/db # sửa lại thành mongo-data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI

volumes:
  mongo-data:
    external: true
    name: post_mongo-data
